const actions = {
    LOGIN : 'LOGIN',
    SIGNOUT : 'SIGNOUT',
    HENT_SOKNADER: 'HENT_SOKNADER',
    FILTRER_SOKNADER: 'FILTRER_SOKNADER',
    CHANGEMAINMENU: 'CHANGEMAINMENU',
    HENT_LOGG: 'HENT_LOGG',
    OPPRETT_LOGG: 'OPPRETT_LOGG',
    HENT_MINE_SOKNADER: 'HENT_MINE_SOKNADER'
}

export default actions;